# Docker Compose for PostgreSQL Database
# Note: This configuration has not been fully tested
# For production deployments, use managed PostgreSQL services (Vercel Postgres, Supabase, Railway)

version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: flex-living-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: flex_living
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
